// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc2wVyFPIn8IRZh6ziCxCOe1vaCauI8MU',
    appId: '1:380457785407:web:1160fd8698640f317a008a',
    messagingSenderId: '380457785407',
    projectId: 'uasppb-b728a',
    authDomain: 'uasppb-b728a.firebaseapp.com',
    storageBucket: 'uasppb-b728a.firebasestorage.app',
    measurementId: 'G-XXCPPNZSEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ab51G9JwhwhJMoIacjHDxXuqai8xNls',
    appId: '1:380457785407:android:7cbc181980cf98197a008a',
    messagingSenderId: '380457785407',
    projectId: 'uasppb-b728a',
    storageBucket: 'uasppb-b728a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6VPmeqjpBQ8_vfLD6LEsf3eBinCDEieg',
    appId: '1:380457785407:ios:f2fe68a1de58c45c7a008a',
    messagingSenderId: '380457785407',
    projectId: 'uasppb-b728a',
    storageBucket: 'uasppb-b728a.firebasestorage.app',
    iosBundleId: 'com.example.uasapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6VPmeqjpBQ8_vfLD6LEsf3eBinCDEieg',
    appId: '1:380457785407:ios:f2fe68a1de58c45c7a008a',
    messagingSenderId: '380457785407',
    projectId: 'uasppb-b728a',
    storageBucket: 'uasppb-b728a.firebasestorage.app',
    iosBundleId: 'com.example.uasapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc2wVyFPIn8IRZh6ziCxCOe1vaCauI8MU',
    appId: '1:380457785407:web:ebb96c1b1b590d367a008a',
    messagingSenderId: '380457785407',
    projectId: 'uasppb-b728a',
    authDomain: 'uasppb-b728a.firebaseapp.com',
    storageBucket: 'uasppb-b728a.firebasestorage.app',
    measurementId: 'G-L0G7ECGHW0',
  );

}